### ISSUE TITLE
onData chunk of data not working

### ISSUE THREAD

**Issue by DarianHarrison** [cleandersonlobo/react-mic#1]

**Comment by cleandersonlobo** [comment]
Have you tried to record in MP3 or other format?

**Comment by tylercollins590** [comment]
I am seeing the same issue with wav. "recordedBlob" is "undefined"

**Comment by TopHatMan** [comment]
That happens because of ondata callback with no blob.

**Comment by licesonw** [comment]
Still struggling with this problem. When I log recordedBlob I get 1000s of "undefined" within seconds. Anyone figured it out? It happens for both wav and mp3.

**Comment by marek357** [comment]
Has this issue been resolved, as it is closed? If so, then what's the solution? Thanks!
