### ISSUE TITLE
Red dot on tab doesn't disappear when stop recording (Chrome)

### ISSUE THREAD

**Issue by felipefutty** [cleandersonlobo/react-mic#5]
I've realised  that using the mimeType `audio/mp3` when it stops the record the red dot on tab of google chrome  (version 78) does not disappear!

The same problema does not happen when using `audio/wav`. 

Checking the code I could fix it by replace the function `stopRecording` of `MicrophoneRecorderMp3` class, with following code:

```
stopRecording() {
    if (mediaRecorder) {
      stream.getAudioTracks().forEach(track => {
        track.stop();
      });
      AudioContext.resetAnalyser();
      this.onStop();

    }
  }
```

**Please, could it be reviewed and released a version fixing it ?**

Note: the same problem happen in Safaria, using the above fix doesn't fix in safaria (it should be better analysed!)

**Comment by cleandersonlobo** [comment]
Thanks @felipefutty  for the contribution and sorry for the delay to implement it.

I fix this in this [commit](https://github.com/cleandersonlobo/react-mic/commit/53a06c9df8c2abbcf7e020d6faebf229ec58d413)
